[[plugins]]
repo = 'Shougo/dein.vim'
merged = 0

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'haya14busa/vim-keeppad'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'itchyny/vim-cursorword'

[[plugins]]
repo = 'haya14busa/unite-ghq'

[[plugins]]
repo = 'k0kubun/unite-git-files'

[[plugins]]
repo = 'lambdalisue/unite-grep-vcs'

[[plugins]]
repo = 'haya14busa/haya14busa-snippets'

[[plugins]]
repo = 'othree/html5.vim'
