[[plugins]]
repo = 'Shougo/dein.vim'
merged = 0

[[plugins]]
repo = 'haya14busa/dein-command.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

# [[plugins]]
# repo = 'haya14busa/vim-keeppad'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'rakr/vim-one'

[[plugins]]
repo = 'itchyny/vim-cursorword'

# [[plugins]]
# repo = 'haya14busa/unite-ghq'

[[plugins]]
repo = 'lambdalisue/unite-grep-vcs'

[[plugins]]
repo = 'haya14busa/haya14busa-snippets'

[[plugins]]
repo = 'othree/html5.vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'posva/vim-vue'

[[plugins]]
repo = 'bfrg/vim-jq'

